version: '3'

services:
  ui:
    build:
      context: ./ui
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/opt/ui
      - /opt/ui/node_modules
    working_dir: /opt/ui

  server:
    build:
      context: ./server
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    links:
      - database:database
    ports:
      - "8080:8080"
    volumes:
      - ./server:/opt/server
      - /opt/server/node_modules
    working_dir: /opt/server
  
  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: hipages
      MYSQL_DATABASE: hipages
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
